export const REGISTER_USER = `REGISTER_USER`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;
export const REGISTER_FAIL = `REGISTER_FAIL`; 

export const LOGIN_USER = `LOGIN_USER`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const LOGIN_FAIL = `LOGIN_FAIL`;

export const UPDATE_USER = `UPDATE_USER`;
export const UPDATE_SUCCESS = `UPDATE_SUCCESS`;
export const UPDATE_FAIL = `UPDATE_FAIL`;

export const GET_PROFILE = `GET_PROFILE`;
export const GET_PROFILE_SUCCESS = `GET_PROFILE_SUCCESS`;
export const GET_PROFILE_FAIL = `GET_PROFILE_FAIL`;

export const GET_PROFILES_LIST = `GET_PROFILES_LIST`;
export const GET_PROFILES_LIST_SUCCESS = `GET_PROFILES_LIST_SUCCESS`;
export const GET_PROFILES_LIST_FAIL = `GET_PROFILES_LIST_FAIL`;

export const UPLOAD_PROJECT_PUBLIC = `UPLOAD_PROJECT_PUBLIC`;
export const UPLOAD_PROJECT_PUBLIC_SUCCESS = `UPLOAD_PROJECT_PUBLIC_SUCCESS`;
export const UPLOAD_PROJECT_PUBLIC_FAIL = `UPLOAD_PROJECT_PUBLIC_FAIL`;

export const UPLOAD_PROJECT_PRIVATE = `UPLOAD_PROJECT_PRIVATE`;
export const UPLOAD_PROJECT_PRIVATE_SUCCESS = `UPLOAD_PROJECT_PRIVATE_SUCCESS`;
export const UPLOAD_PROJECT_PRIVATE_FAIL = `UPLOAD_PROJECT_PRIVATE_FAIL`;

export const GET_SELECTED_PROFILE = `GET_SELECTED_PROFILE`;
export const GET_SELECTED_PROFILE_SUCCESS = `GET_SELECTED_PROFILE_SUCCESS`;
export const GET_SELECTED_PROFILE_FAIL = `GET_SELECTED_PROFILE_FAIL`;

export const GET_PROJECT = `GET_PROJECT`;
export const GET_PROJECT_SUCCESS = `GET_PROJECT_SUCCESS`;
export const GET_PROJECT_FAIL = `GET_PROJECT_FAIL`;

export const SEND_COMMENT_SUCCESS = `SEND_COMMENT_SUCCESS`;
export const SEND_COMMENT_FAIL = `SEND_COMMENT_FAIL`;

export const SEND_RATING_SUCCESS = `SEND_RATING_SUCCESS`;
export const SEND_RATING_FAIL = `SEND_RATING_FAIL`;

export const SEND_ACCEPT_OR_DENY_SUCCESS = `SEND_ACCEPT_OR_DENY_SUCCESS`;
export const SEND_ACCEPT_OR_DENY_FAIL = `SEND_ACCEPT_OR_DENY_FAIL`; 