export const REGISTER_USER = `REGISTER_USER`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;
export const REGISTER_FAIL = `REGISTER_FAIL`; 

export const LOGIN_USER = `LOGIN_USER`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const LOGIN_FAIL = `LOGIN_FAIL`;

export const UPDATE_USER = `UPDATE_USER`;
export const UPDATE_SUCCESS = `UPDATE_SUCCESS`;
export const UPDATE_FAIL = `UPDATE_FAIL`;

export const GET_PROFILE = `GET_PROFILE`;
export const GET_PROFILE_SUCCESS = `GET_PROFILE_SUCCESS`;
export const GET_PROFILE_FAIL = `GET_PROFILE_FAIL`;

export const GET_PROFILES_LIST = `GET_PROFILES_LIST`;
export const GET_PROFILES_LIST_SUCCESS = `GET_PROFILES_LIST_SUCCESS`;
export const GET_PROFILES_LIST_FAIL = `GET_PROFILES_LIST_FAIL`;

export const UPLOAD_PROJECT_PUBLIC = `UPLOAD_PROJECT_PUBLIC`;
export const UPLOAD_PROJECT_PUBLIC_SUCCESS = `UPLOAD_PROJECT_PUBLIC_SUCCESS`;
export const UPLOAD_PROJECT_PUBLIC_FAIL = `UPLOAD_PROJECT_PUBLIC_FAIL`;

export const UPLOAD_PROJECT_PRIVATE = `UPLOAD_PROJECT_PRIVATE`;
export const UPLOAD_PROJECT_PRIVATE_SUCCESS = `UPLOAD_PROJECT_PRIVATE_SUCCESS`;
export const UPLOAD_PROJECT_PRIVATE_FAIL = `UPLOAD_PROJECT_PRIVATE_FAIL`;

export const GET_SELECTED_PROFILE = `GET_SELECTED_PROFILE`;
export const GET_SELECTED_PROFILE_SUCCESS = `GET_SELECTED_PROFILE_SUCCESS`;
export const GET_SELECTED_PROFILE_FAIL = `GET_SELECTED_PROFILE_FAIL`;

export const GET_EMAIL = `GET_EMAIL`;
export const GET_EMAIL_SUCCESS = `GET_EMAIL_SUCCESS`;
export const GET_EMAIL_FAIL = `GET_EMAIL_FAIL`;

export const GET_PROJECT = `GET_PROJECT`;
export const GET_PROJECT_SUCCESS = `GET_PROJECT_SUCCESS`;
export const GET_PROJECT_FAIL = `GET_PROJECT_FAIL`;

export const SEND_PROJECT_FINISHED = `SEND_PROJECT_FINISHED`;
export const SEND_PROJECT_FINISHED_SUCCESS = `SEND_PROJECT_FINISHED_SUCCESS`;
export const SEND_PROJECT_FINISHED_FAIL = `SEND_PROJECT_FINISHED_FAIL`;

export const GET_PUBLIC_PROJECT = `GET_PUBLIC_PROJECT`;
export const GET_PUBLIC_PROJECT_SUCCESS = `GET_PUBLIC_PROJECT_SUCCESS`;
export const GET_PUBLIC_PROJECT_FAIL = `GET_PUBLIC_PROJECT_FAIL`;

export const SEND_COMMENT = `SEND_COMMENT`;
export const SEND_COMMENT_SUCCESS = `SEND_COMMENT_SUCCESS`;
export const SEND_COMMENT_FAIL = `SEND_COMMENT_FAIL`;

export const SEND_RATING = `SEND_RATING`;
export const SEND_RATING_SUCCESS = `SEND_RATING_SUCCESS`;
export const SEND_RATING_FAIL = `SEND_RATING_FAIL`;

export const DELETE_PROJECT = `DELETE_PROJECT`;
export const DELETE_PROJECT_SUCCESS = `DELETE_PROJECT_SUCCESS`;
export const DELETE_PROJECT_FAIL = `DELETE_PROJECT_FAIL`; 

export const SEND_ACCEPT_OR_DENY = `SEND_ACCEPT_OR_DENY`;
export const SEND_ACCEPT_OR_DENY_SUCCESS = `SEND_ACCEPT_OR_DENY_SUCCESS`;
export const SEND_ACCEPT_OR_DENY_FAIL = `SEND_ACCEPT_OR_DENY_FAIL`; 

export const PROJECT_RECEIVED = `PROJECT_RECEIVED`;
export const PROJECT_RECEIVED_SUCCESS = `PROJECT_RECEIVED_SUCCESS`;
export const PROJECT_RECEIVED_FAIL = `PROJECT_RECEIVED_FAIL`; 

export const POST_WORK_ON_PUBLIC_PROJECT = `POST_WORK_ON_PUBLIC_PROJECT`;
export const POST_WORK_ON_PUBLIC_PROJECT_SUCCESS = `POST_WORK_ON_PUBLIC_PROJECT_SUCCESS`;
export const POST_WORK_ON_PUBLIC_PROJECT_FAIL = `POST_WORK_ON_PUBLIC_PROJECT_FAIL`;

export const GET_FREELANCERS_WORKING_ON_PUBLIC = `GET_FREELANCERS_WORKING_ON_PUBLIC`;
export const GET_FREELANCERS_WORKING_ON_PUBLIC_SUCCESS = `GET_FREELANCERS_WORKING_ON_PUBLIC_SUCCESS`;
export const GET_FREELANCERS_WORKING_ON_PUBLIC_FAIL = `GET_FREELANCERS_WORKING_ON_PUBLIC_FAIL`;

export const HIRE_THIS_FREELANCER = `HIRE_THIS_FREELANCER`;
export const HIRE_THIS_FREELANCER_SUCCESS = `HIRE_THIS_FREELANCER_SUCCESS`;
export const HIRE_THIS_FREELANCER_FAIL = `HIRE_THIS_FREELANCER_FAIL`;

export const CLEAR_EMAIL = `CLEAR_EMAIL`